### ISSUE TITLE
some doubts

### ISSUE THREAD

**Issue by valleyPioneer** [binbin594738977/AndroidFramework-soundCode#1]
这样在Android Studio中打开无法构建索引，也无法点击跳转。同样地，这些源代码也能在<sdk location>/sources/android-xx下找到，不过还是感谢分享！

**Comment by binbin594738977** [comment]
源码没有索引 可以在指定版本main/java 右键选择mark directory as  选择 Source Root 这样就能建索引了
比/ sources / android-xx的代码代码更全!  基本没有报错

**Comment by binbin594738977** [comment]
> 这样在Android Studio中打开无法构建索引，也无法点击重定向。同样地，这些源代码也能在/ sources / android-xx下找到，不过还是感谢分享！

**Comment by binbin594738977** [comment]
> 这样在Android Studio中打开无法构建索引，也无法点击重定向。同样地，这些源代码也能在/ sources / android-xx下找到，不过还是感谢分享！

原始代码没有索引可以在指定版本main / java快捷选择中将目录标记为选择Source Root这样可以建立索引了
比/ sources / android-xx的代码代码更全！基本没有报错

**Comment by binbin594738977** [comment]
> 原始代码没有索引可以在指定版本中main / java快捷选择中将目录标记为选择Source Root这样可以建立索引了
> 比/ sources / android-xx的代码编码更全！基本没有报错

原始代码没有索引可以在指定版本中main / java目录选择Mark directory as然后选择Source Root这样可以建立索引了
比/ sources / android-xx的代码编码更全！基本没有报错

**Comment by valleyPioneer** [comment]
> > 原始代码没有索引可以在指定版本中main / java快捷选择中将目录标记为选择Source Root这样可以建立索引了
> > 比/ sources / android-xx的代码编码更全！基本没有报错
> 
> 原始代码没有索引可以在指定版本中main / java目录选择Mark directory as然后选择Source Root这样可以建立索引了
> 比/ sources / android-xx的代码编码更全！基本没有报错

感谢解答！
